### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by vibhavagarwal5**
# Fixes # 

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [yes ] I have read the [Contribution Guide] and my PR follows them.
- [yes ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- updated the .travis.yml file with the CodeCov data
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-python?pullRequest=54) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-python?pullRequest=54) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-python?pullRequest=54) it.</sub>

**Comment by mbernier** [comment]
@vibhavagarwal5

We can’t merge your PR without the CLA being signed. 

[ ] **Sign the CLA before November 3rd**
[ ] Tag @mbernier and @thinkingserious to let us know it is signed 

Then we will comment with a link to get your shirt!

**Comment by vibhavagarwal5** [comment]
@mbernier @thinkingserious i have signed the CLA.
kindly check and do let me know if i have to do something else.
Do update me regarding the shirt too.

**Comment by thinkingserious** [comment]
Thanks @vibhavagarwal5!

[Here](https://dx.sendgrid.com/swag) is the link :)

**Pull request closed without merging**
