### PR TITLE
chore: Follows PEP8 standard

### PR DESCRIPTION
**Pull request by Madhur96**
# Fixes https://github.com/sendgrid/smtpapi-python/issues/49

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Follows PEP8 standards

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-python?pullRequest=50) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-python?pullRequest=50) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-python?pullRequest=50) it.</sub>

**Comment by Madhur96** [comment]
@ksigler7  please review

**Comment by thinkingserious** [comment]
Hi @Madhur96,

I think you will need to add a file [similar to this one](https://github.com/sendgrid/smtpapi-ruby/blob/master/.codeclimate.yml) at the root level.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hi @Madhur96,

Could you please resolve the merge conflicts?

Thanks!

With Best Regards,l

Elmer

**Comment by thinkingserious** [comment]
Hello @Madhur96,

We have a [few more errors](https://travis-ci.com/github/sendgrid/smtpapi-python/builds/202917592) to resolve before this can be merged. Would you please take a look?

Thank you!

With best regards,

Elmer

**Comment by thinkingserious** [comment]
Closing until PR feedback is addressed.

**Pull request closed without merging**
