### PR TITLE
fix: "similar-code" issue in smtpapi/__init__.py 

### LINKED ISSUE #46: Fix "similar-code" issue in smtpapi/__init__.py
Similar blocks of code found in 4 locations. Consider refactoring.

Check the issues mentioned here: 
https://codeclimate.com/github/sendgrid/smtpapi-python/smtpapi/__init__.py

### PR DESCRIPTION
**Pull request by andre8359**
<!--
We appreciate the effort for this pull request but before that please make sure you read the contribution guidelines given above, then fill out the blanks below.

Please enter each Issue number you are resolving in your PR after one of the following words [Fixes, Closes, Resolves]. This will auto-link these issues and close them when this PR is merged!
e.g. 
Fixes #46 

# Fixes # 
Fix "similar-code" issue in smtpapi/__init__.py 

### Checklist
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.

### Short description of what this PR does:
- Refactor methods for reuse code
- Make changes on this file for use PEP8 codestyle

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-python?pullRequest=53) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-python?pullRequest=53) before we can accept your contribution.<br/><hr/>**André Mateus Rodrigues Dantas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-python?pullRequest=53) it.</sub>

**Comment by thinkingserious** [comment]
@andre8359

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by misterdorm** [comment]
Duplicated by #55  and #62

**Comment by thinkingserious** [comment]
Hello @andre8359,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
